Repository I-on-I/OO-s-Library-BE, pull requests merged in 2024-04, with the labels that each got.

#27 < feat >: security + oauth2 setting + 회원 엔티티
  .gitignore
  build.gradle
  build/classes/java/main/com/projectif/ooslibrary/IndexController.class
  build/classes/java/main/com/projectif/ooslibrary/OOsLibraryApplication.class
  build/classes/java/main/com/projectif/ooslibrary/config/QueryDslConfig.class
  build/classes/java/main/com/projectif/ooslibrary/config/SecurityConfig.class
  build/resources/main/application.yml
  build/resources/main/templates/index/index.html
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/projectif/ooslibrary/OOsLibraryApplication.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/config/auditing/BaseEntity.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/domain/Member.java
  src/main/java/com/projectif/ooslibrary/member/domain/MyLibrary.java
  src/main/java/com/projectif/ooslibrary/member/domain/Role.java
  src/main/java/com/projectif/ooslibrary/member/repository/MemberRepository.java
  src/main/java/com/projectif/ooslibrary/security/CustomUserDetailsService.java
  src/main/java/com/projectif/ooslibrary/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2Attribute.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
  src/main/java/com/projectif/ooslibrary/team/domain/Team.java
  src/main/resources/application.yml
  src/main/resources/templates/index/index.html
  src/main/resources/templates/test/login.html
Labels: feat, fix

#29 < feat >: 회원 Controller CRUD 구현
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
Labels: feat

#30 < fix >: Member 엔티티 정리
  .gitignore
  src/main/java/com/projectif/ooslibrary/member/domain/Member.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
Labels: fix

#31 feat: 책 전체 리스트업 기능 추가 완료
  build.gradle
  src/main/java/com/projectif/ooslibrary/book/BookController.java
  src/main/java/com/projectif/ooslibrary/book/BookDTO.java
  src/main/java/com/projectif/ooslibrary/book/BookRepository.java
  src/main/java/com/projectif/ooslibrary/book/BookService.java
  src/main/java/com/projectif/ooslibrary/book/domain/Book.java
Labels: feat

#32 test , fix : 회원 비밀번호 Bcrypt 적용
  build.gradle
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/config/WebMvcConfig.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/controller/book/controller/Example.java
  src/main/java/com/projectif/ooslibrary/member/domain/Member.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberJoinRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberResponseDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberUpdateRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/repository/MemberRepository.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberService.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
  src/main/java/com/projectif/ooslibrary/my_library/domain/MyLibrary.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
  src/main/resources/application.yml
  src/main/resources/templates/index/index.html
  src/test/java/com/projectif/ooslibrary/member/service/MemberServiceImplTest.java
Labels: fix, test

#34 < fix >: login test - react
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/config/WebMvcConfig.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/security/CustomAuthFailureHandler.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
Labels: fix, refactor

#35 < feat >: member dto - validation 추가
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberJoinRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberUpdateRequestDTO.java
Labels: feat

#36 < fix >: nid.naver
  src/main/java/com/projectif/ooslibrary/config/WebMvcConfig.java
Labels: fix

#43 < feat fix >: 회원 마이페이지 비밀번호 체크 기능 외 3
  src/main/java/com/projectif/ooslibrary/book/BookController.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberCheckPasswordRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberJoinRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberUpdateRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/repository/MemberRepository.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberService.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
Labels: feat, fix

#44 < fix >: 회원 마이페이지 비밀번호 체크 인코딩 부분 수정
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
Labels: fix

#45 <fix> url 수정
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
Labels: fix

#46 <fix> member 수정 / 삭제 기능 수정
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberCheckPasswordRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
Labels: fix

#47 feat: BookText 기능 추가
  src/main/java/com/projectif/ooslibrary/book/BookController.java
  src/main/java/com/projectif/ooslibrary/book/BookService.java
  src/main/java/com/projectif/ooslibrary/book/BookTextDTO.java
Labels: feat

#49 <feat> MemberExceptionController 구현
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/exceptions/MemberExceptionController.java
Labels: feat

#52 <feat> NoSuchMemberException 구현
  src/main/java/com/projectif/ooslibrary/exceptions/MemberExceptionController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/exception/MemberException.java
  src/main/java/com/projectif/ooslibrary/member/exception/NoSuchMemberException.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
  src/main/java/com/projectif/ooslibrary/security/CustomUserDetailsService.java
  src/main/java/com/projectif/ooslibrary/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
Labels: feat

#53 <fix> :CompileQueryDsl 문제 세팅 변경
  build.gradle
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
  src/test/java/com/projectif/ooslibrary/member/service/MemberServiceImplTest.java
Labels: fix

#54 <fix> : oauth2 로그인 성공 반환 변경
  src/main/java/com/projectif/ooslibrary/exceptions/MemberExceptionController.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/exception/OAuth2LoginNoSessionValueException.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
Labels: fix

#59 <feat> : mail 코드 인증 메일 기능
  build.gradle
  src/main/java/com/projectif/ooslibrary/config/MailConfig.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/config/auditing/BaseEntity.java
  src/main/java/com/projectif/ooslibrary/exceptions/MemberExceptionController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MailController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/domain/Mail.java
  src/main/java/com/projectif/ooslibrary/member/dto/EmailVerifyRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/repository/MailRepository.java
  src/main/java/com/projectif/ooslibrary/member/repository/MemberRepository.java
  src/main/java/com/projectif/ooslibrary/member/service/MailService.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: feat

#58 feat: 코멘트 기능 구현
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentController.java
  src/main/java/com/projectif/ooslibrary/comment/domain/CommentVO.java
  src/main/java/com/projectif/ooslibrary/comment/dto/CommentResponseDTO.java
  src/main/java/com/projectif/ooslibrary/comment/dto/PageInfo.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentService.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentServiceImpl.java
  src/main/java/com/projectif/ooslibrary/mapper/CommentMapper.java
  src/main/resources/mapper/comment/commentMapper.xml
Labels: feat

#62 fix: getBookPath Optional 사용하는데 null반환 하지않게 수정
  src/main/java/com/projectif/ooslibrary/book/BookService.java
Labels: fix

#63 <feat> : mail 임시 비밀번호 / member 커스텀 예외처리
  src/main/java/com/projectif/ooslibrary/config/MailConfig.java
  src/main/java/com/projectif/ooslibrary/exceptions/MemberExceptionController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MailController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/domain/Mail.java
  src/main/java/com/projectif/ooslibrary/member/domain/Member.java
  src/main/java/com/projectif/ooslibrary/member/dto/EmaiCodelVerifyDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/EmailVerifyRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberJoinRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberUpdateRequestDTO.java
  src/main/java/com/projectif/ooslibrary/member/exception/MailNotVerifiedException.java
  src/main/java/com/projectif/ooslibrary/member/exception/NoSuchVerifyCodeException.java
  src/main/java/com/projectif/ooslibrary/member/repository/MailRepository.java
  src/main/java/com/projectif/ooslibrary/member/repository/MemberRepository.java
  src/main/java/com/projectif/ooslibrary/member/service/MailService.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: feat, fix

#65 <fix> : 잡다 예외 + Board QueryDsl 간단 적용
  build.gradle
  src/main/java/com/projectif/ooslibrary/board/controller/BoardController.java
  src/main/java/com/projectif/ooslibrary/board/domain/Board.java
  src/main/java/com/projectif/ooslibrary/board/repository/BoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/repository/CutsomBoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/repository/CutsomBoardRepositoryImpl.java
  src/main/java/com/projectif/ooslibrary/board/service/BoardService.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/exceptions/MemberExceptionController.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/exception/MailNotSendException.java
  src/main/java/com/projectif/ooslibrary/member/service/MailService.java
  src/main/java/com/projectif/ooslibrary/team/repository/TeamRepository.java
  src/test/java/com/projectif/ooslibrary/OOsLibraryApplicationTests.java
  src/test/java/com/projectif/ooslibrary/member/service/MemberServiceImplTest.java
Labels: feat, fix

#67 <refactor> : board 관련 기능
  src/main/java/com/projectif/ooslibrary/board/controller/BoardController.java
  src/main/java/com/projectif/ooslibrary/board/domain/Board.java
  src/main/java/com/projectif/ooslibrary/board/exception/NoSuchBoardException.java
  src/main/java/com/projectif/ooslibrary/board/repository/BoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/repository/CutsomBoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/repository/CutsomBoardRepositoryImpl.java
  src/main/java/com/projectif/ooslibrary/board/service/BoardService.java
  src/main/java/com/projectif/ooslibrary/exceptions/BoardExceptionController.java
  src/main/java/com/projectif/ooslibrary/exceptions/MemberExceptionController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/exception/SessionMemberNotMatchException.java
Labels: fix, refactor

#68 <fix> : board repo 오류 수정
  src/main/java/com/projectif/ooslibrary/board/repository/BoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/service/BoardService.java
Labels: fix

#69 feat: 코멘트 좋아요, 신고 기능 추가
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentController.java
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentLikeController.java
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentReportController.java
  src/main/java/com/projectif/ooslibrary/comment/domain/CommentLikeVO.java
  src/main/java/com/projectif/ooslibrary/comment/domain/CommentReportVO.java
  src/main/java/com/projectif/ooslibrary/comment/dto/CommentLikeRequestDTO.java
  src/main/java/com/projectif/ooslibrary/comment/dto/CommentReportRequestDTO.java
  src/main/java/com/projectif/ooslibrary/comment/dto/CommentRequestDTO.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentLikeService.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentLikeServiceImpl.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentReportService.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentReportServiceImpl.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentService.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentServiceImpl.java
  src/main/java/com/projectif/ooslibrary/mapper/CommentLikeMapper.java
  src/main/java/com/projectif/ooslibrary/mapper/CommentMapper.java
  src/main/java/com/projectif/ooslibrary/mapper/CommentReportMapper.java
  src/main/resources/mapper/comment/CommentLikeMapper.xml
  src/main/resources/mapper/comment/CommentReportMapper.xml
  src/main/resources/mapper/comment/commentMapper.xml
Labels: feat

#70 <fix> : my library 회원가입 시, 등록
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/domain/Member.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
  src/main/java/com/projectif/ooslibrary/my_library/controller/Example.java
  src/main/java/com/projectif/ooslibrary/my_library/domain/MyLibrary.java
  src/main/java/com/projectif/ooslibrary/my_library/repository/MyLibraryRepository.java
Labels: feat, fix

#72 test: 코멘트 기능 테스트
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentController.java
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentReportController.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentReportService.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentService.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentServiceImpl.java
  src/main/java/com/projectif/ooslibrary/mapper/CommentMapper.java
  src/main/java/com/projectif/ooslibrary/mapper/CommentReportMapper.java
  src/main/resources/mapper/comment/CommentLikeMapper.xml
  src/main/resources/mapper/comment/CommentReportMapper.xml
  src/main/resources/mapper/comment/commentMapper.xml
Labels: test

#76 <feat> : thymeleaf bootstrap5 theme
  build.gradle
  src/main/java/com/projectif/ooslibrary/IndexController.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/resources/static/assets/favicon.ico
  src/main/resources/static/assets/profile.png
  src/main/resources/static/assets/profile2.png
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index/contact.html
  src/main/resources/templates/index/index.html
  src/main/resources/templates/index/projects.html
  src/main/resources/templates/index/resume.html
Labels: feat

#77 <feat, fix> thymeleaf 공사중
  src/main/java/com/projectif/ooslibrary/IndexController.java
  src/main/java/com/projectif/ooslibrary/board/controller/BoardController.java
  src/main/java/com/projectif/ooslibrary/board/dto/BoardResponseDTO.java
  src/main/java/com/projectif/ooslibrary/board/service/BoardService.java
  src/main/java/com/projectif/ooslibrary/book/domain/Book.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MailController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberResponseDTO.java
  src/main/java/com/projectif/ooslibrary/member/repository/MemberRepository.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryController.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryService.java
  src/main/java/com/projectif/ooslibrary/my_library/domain/BookPlus.java
  src/main/java/com/projectif/ooslibrary/my_library/domain/MyLibrary.java
  src/main/java/com/projectif/ooslibrary/security/oauth/OAuth2SuccessHandler.java
  src/main/resources/templates/boards/boardList.html
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/401.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/index/index.html
  src/main/resources/templates/layout/default_layout.html
  src/main/resources/templates/layout/fragments/footer.html
  src/main/resources/templates/layout/fragments/head.html
  src/main/resources/templates/layout/fragments/nav.html
  src/main/resources/templates/members/join.html
  src/main/resources/templates/members/myLibrary.html
  src/main/resources/templates/test/login.html
Labels: feat, fix

#78 <fix, refactor> thymeleaf setting 2
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/config/WebMvcConfig.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/team/controller/Example.java
  src/main/java/com/projectif/ooslibrary/team/controller/TeamController.java
  src/main/java/com/projectif/ooslibrary/team/service/TeamService.java
  src/main/resources/templates/layout/fragments/nav.html
  src/main/resources/templates/members/join.html
  src/main/resources/templates/members/myLibrary.html
  src/main/resources/templates/team/team.html
Labels: fix, refactor

#79 <refactor> : thymeleaf myLibrary / login
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MailController.java
  src/main/resources/templates/login/login.html
  src/main/resources/templates/mail/findId.html
  src/main/resources/templates/mail/findPassword.html
  src/main/resources/templates/members/findId.html
  src/main/resources/templates/members/myLibrary.html
  src/main/resources/templates/test/login.html
Labels: refactor

#80 feat: 읽은책 이력 저장 기능 구현
  src/main/java/com/projectif/ooslibrary/book_calendar/Book_calendarDTO.java
  src/main/java/com/projectif/ooslibrary/book_calendar/Book_calendarRepository.java
  src/main/java/com/projectif/ooslibrary/book_calendar/controller/Book_calendarController.java
  src/main/java/com/projectif/ooslibrary/book_calendar/domain/Book_calendar.java
  src/main/java/com/projectif/ooslibrary/book_calendar/service/Book_calendarService.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryController.java
  src/main/java/com/projectif/ooslibrary/my_library/domain/MyLibrary.java
Labels: feat

#82 feat: 읽은책 이력 관련 정보 가져와 res
  src/main/java/com/projectif/ooslibrary/book/BookController.java
  src/main/java/com/projectif/ooslibrary/book/BookService.java
  src/main/java/com/projectif/ooslibrary/book_calendar/Book_calendarDTO.java
  src/main/java/com/projectif/ooslibrary/book_calendar/Book_calendarRepository.java
  src/main/java/com/projectif/ooslibrary/book_calendar/controller/Book_calendarController.java
  src/main/java/com/projectif/ooslibrary/book_calendar/domain/BookCalendar.java
  src/main/java/com/projectif/ooslibrary/book_calendar/service/Book_calendarService.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryController.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryService.java
  src/main/java/com/projectif/ooslibrary/my_library/domain/BookPlus.java
  src/main/java/com/projectif/ooslibrary/my_library/domain/MyLibrary.java
  src/main/java/com/projectif/ooslibrary/my_library/repository/BookPlusRepository.java
  src/main/resources/templates/layout/fragments/nav.html
  src/main/resources/templates/library/bookplus.html
Labels: feat

#83 fix: 책추가 기능 오류 해결 & 에러메세지 추가
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryController.java
  src/main/resources/templates/library/bookplus.html
Labels: fix

#84 <refactor> : thymeleaf myLibrary / login
  src/main/java/com/projectif/ooslibrary/member/controller/MailController.java
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
  src/main/java/com/projectif/ooslibrary/member/service/MailService.java
  src/main/resources/templates/layout/fragments/nav.html
  src/main/resources/templates/mail/findId.html
  src/main/resources/templates/mail/findPassword.html
  src/main/resources/templates/members/join.html
  src/main/resources/templates/members/memberUpdate.html
  src/main/resources/templates/team/team.html
Labels: feat, refactor

#85 <refactor> : thymeleaf 팀 서재
  src/main/java/com/projectif/ooslibrary/member/domain/Member.java
  src/main/java/com/projectif/ooslibrary/team/controller/TeamController.java
  src/main/java/com/projectif/ooslibrary/team/domain/Team.java
  src/main/java/com/projectif/ooslibrary/team/service/TeamService.java
  src/main/resources/templates/members/myLibrary.html
  src/main/resources/templates/team/add.html
  src/main/resources/templates/team/team.html
Labels: feat

#87 <refactor> : thymeleaf footer 수정
  src/main/resources/templates/layout/fragments/footer.html
Labels: refactor

#88 <refactor> : 회원 수정 - 프로필 선택
  src/main/resources/templates/layout/fragments/nav.html
  src/main/resources/templates/members/memberUpdate.html
  src/main/resources/templates/team/team.html
Labels: refactor

#89 <refactor> : 문의 CRUD 완성 및 폰트/css 변경
  src/main/java/com/projectif/ooslibrary/board/controller/BoardController.java
  src/main/java/com/projectif/ooslibrary/board/domain/Board.java
  src/main/java/com/projectif/ooslibrary/board/dto/BoardInsertDTO.java
  src/main/java/com/projectif/ooslibrary/board/dto/BoardUpdateDTO.java
  src/main/java/com/projectif/ooslibrary/board/repository/BoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/service/BoardService.java
  src/main/resources/static/assets/btnG_완성형.png
  src/main/resources/static/css/styles.css
  src/main/resources/templates/boards/boardList.html
  src/main/resources/templates/boards/boardOne.html
  src/main/resources/templates/boards/boardUpdateForm.html
  src/main/resources/templates/boards/boardWriteForm.html
  src/main/resources/templates/index/index.html
  src/main/resources/templates/layout/fragments/footer.html
  src/main/resources/templates/layout/fragments/head.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/members/memberUpdate.html
Labels: feat, fix, refactor

#90 <refactor> : 문의 상세정보 변경
  src/main/java/com/projectif/ooslibrary/board/controller/BoardController.java
  src/main/java/com/projectif/ooslibrary/board/dto/BoardResponseDTO.java
  src/main/java/com/projectif/ooslibrary/board/repository/BoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/service/BoardService.java
  src/main/resources/templates/boards/boardList.html
  src/main/resources/templates/boards/boardOne.html
Labels: refactor

#91 <refactor> sweetAlert2 라이브러리 적용
  src/main/resources/static/js/library.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/boards/boardOne.html
  src/main/resources/templates/layout/fragments/head.html
  src/main/resources/templates/mail/findId.html
  src/main/resources/templates/mail/findPassword.html
  src/main/resources/templates/members/findId.html
  src/main/resources/templates/members/memberUpdate.html
  src/main/resources/templates/team/team.html
Labels: feat, refactor

#93 <refactor> : sweetAlert2 적용
  src/main/resources/static/css/styles.css
  src/main/resources/templates/boards/boardUpdateForm.html
  src/main/resources/templates/mail/findId.html
  src/main/resources/templates/mail/findPassword.html
  src/main/resources/templates/members/join.html
  src/main/resources/templates/members/memberUpdate.html
  src/main/resources/templates/team/team.html
Labels: refactor

#94 fix : email 인증 수행 에러 fix
  src/main/java/com/projectif/ooslibrary/member/controller/MailController.java
  src/main/java/com/projectif/ooslibrary/member/dto/EmailCodeVerifyDTO.java
  src/main/resources/templates/mail/findId.html
  src/main/resources/templates/mail/findPassword.html
  src/main/resources/templates/members/join.html
Labels: fix

#95 feat: 도서관 카테고리 기능 추가
  src/main/java/com/projectif/ooslibrary/book/BookController.java
  src/main/java/com/projectif/ooslibrary/book/BookService.java
  src/main/resources/templates/library/bookplus.html
Labels: feat

#96 Gyuchan
  src/main/java/com/projectif/ooslibrary/member/controller/MemberController.java
Labels: fix

#100 feat: admin페이지 추가
  src/main/java/com/projectif/ooslibrary/admin/controller/AdMemberController.java
  src/main/java/com/projectif/ooslibrary/admin/domain/MemberVO.java
  src/main/resources/mapper/AdMemberMapper.xml
  src/main/resources/templates/pages/admin/adminPage.html
  src/main/resources/templates/pages/admin/memberList.html
Labels: feat

#101 fix: mapper 경로 재설정
  src/main/resources/mapper/admin/AdMemberMapper.xml
  src/main/resources/mapper/comment/CommentLikeMapper.xml
  src/main/resources/mapper/comment/CommentReportMapper.xml
  src/main/resources/mapper/comment/commentMapper.xml
Labels: fix

#102 Gyuchan
  src/main/java/com/projectif/ooslibrary/board/controller/BoardController.java
  src/main/java/com/projectif/ooslibrary/board/domain/Board.java
  src/main/java/com/projectif/ooslibrary/board/dto/BoardResponseDTO.java
  src/main/java/com/projectif/ooslibrary/board/repository/CutsomBoardRepository.java
  src/main/java/com/projectif/ooslibrary/board/repository/CutsomBoardRepositoryImpl.java
  src/main/java/com/projectif/ooslibrary/board/service/BoardService.java
  src/main/java/com/projectif/ooslibrary/member/controller/LoginController.java
  src/main/java/com/projectif/ooslibrary/member/dto/MemberResponseDTO.java
  src/main/java/com/projectif/ooslibrary/member/service/MemberServiceImpl.java
  src/main/resources/templates/boards/boardList.html
  src/main/resources/templates/index/index.html
Labels: fix

#103 feat: 내 서재 책 삭제 api 생성
  src/main/java/com/projectif/ooslibrary/book_calendar/Book_calendarRepository.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryController.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryService.java
  src/main/java/com/projectif/ooslibrary/my_library/repository/BookPlusRepository.java
  src/main/resources/templates/library/bookplus.html
  src/main/resources/templates/members/myLibrary.html
Labels: feat

#105 refactor : ㄷㄷ
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentController.java
Labels: fix

#106 feat: ebook
  src/main/java/com/projectif/ooslibrary/book/BookController.java
  src/main/java/com/projectif/ooslibrary/book/BookService.java
  src/main/java/com/projectif/ooslibrary/book/BookTextDTO.java
  src/main/java/com/projectif/ooslibrary/book_calendar/controller/Book_calendarController.java
  src/main/java/com/projectif/ooslibrary/config/SecurityConfig.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryController.java
  src/main/java/com/projectif/ooslibrary/my_library/My_libraryService.java
  src/main/resources/static/assets/EAF27272-05DC-4D15-A1AC-249028AD6DB8_1_105_c.jpeg
  src/main/resources/static/css/e_book.css
  src/main/resources/static/js/e_book.js
  src/main/resources/templates/eBook/e_book.html
  src/main/resources/templates/members/myLibrary.html
Labels: feat

#107 fix: 책보여주는 css
  src/main/resources/static/css/styles.css
  src/main/resources/templates/library/bookCalendar.html
  src/main/resources/templates/library/bookplus.html
  src/main/resources/templates/members/myLibrary.html
Labels: fix

#108 fix: 책보여주는 css 추가 수정
  src/main/resources/templates/library/bookCalendar.html
  src/main/resources/templates/library/bookplus.html
  src/main/resources/templates/members/myLibrary.html
Labels: fix

#109 fix: 북캘린더 css 변경
  src/main/resources/templates/eBook/e_book.html
  src/main/resources/templates/library/bookCalendar.html
  src/main/resources/templates/library/bookplus.html
Labels: fix

#110 MyLibraryBookDTO
  src/main/java/com/projectif/ooslibrary/my_library/MyLibraryBookDTO.java
Labels: fix

#112 feat: comment
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentController.java
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentLikeController.java
  src/main/java/com/projectif/ooslibrary/comment/controller/CommentReportController.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentLikeService.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentLikeServiceImpl.java
  src/main/java/com/projectif/ooslibrary/comment/service/CommentReportService.java
  src/main/java/com/projectif/ooslibrary/mapper/CommentLikeMapper.java
  src/main/resources/mapper/comment/CommentLikeMapper.xml
  src/main/resources/mapper/comment/commentMapper.xml
  src/main/resources/templates/members/commentReport.html
  src/main/resources/templates/members/commentUpdate.html
  src/main/resources/templates/members/myLibrary.html
Labels: feat
